version: '3'
services:
    service1:
        image: jwilder/whoami
        container_name: service1
        hostname: service1
        ports:
          - "8000"

    service2:
        image: strm/helloworld-http
        container_name: service2
        hostname: service2
        ports:
          - "80"

    nginx:
        build: .
        image: 0x8861/nginx-le:stable
        hostname: nginx
        restart: always
        container_name: nginx
        depends_on:
          - "service1"
          - "service2"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/service.conf:/etc/nginx/service.conf
        ports:
            - "80:80"
            - "443:443"
            - "8443:8443"

        environment:
            - NGINX_LE_TZ=GMT
            - NGINX_LE_LETSENCRYPT=true
            - NGINX_LE_EMAIL=youremail@example.com
            - NGINX_LE_FQDN=yourdomain.com
            #- NGINX_LE_SSL_CERT=le-crt.pem
            #- NGINX_LE_SSL_KEY=le-key.pem
            #- NGINX_LE_SSL_CHAIN_CERT=le-chain-crt.pem
